name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg dependencies
        uses: actions/cache@v3
        with:
          path: ~/.vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build g++ cmake

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git --depth=1
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg dependencies
        uses: actions/cache@v3
        with:
          path: C:\vcpkg\installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg --depth=1
          C:\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Configure CMake
        run: |
          cmake -B build -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release
