name: Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - {os: windows-latest, compiler: msvc}
          - {os: ubuntu-latest, compiler: gcc}
    
    runs-on: ${{ matrix.config.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install vcpkg
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        if [ "${{ matrix.config.os }}" == "windows-latest" ]; then
          ./vcpkg/bootstrap-vcpkg.bat
        else
          ./vcpkg/bootstrap-vcpkg.sh
        fi
        ./vcpkg/vcpkg integrate install

    - name: Install Linux Dependencies
      if: matrix.config.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        if [ "${{ matrix.config.os }}" == "windows-latest" ]; then
          cmake --build . --config Release
        else
          make -j $(nproc) CoffeeEditor
        fi